appset:
  clustername: cluster1
  argoProject: exploitation
  type: test
  default:
    ServerSideApply: true
    CreateNamespace: true
    repoUrl: "https://github.com/ArnaudCHT/appset.git"
    branch: "main"
    syncPolicy:
      autoSync: true
      prune: true
      selfHeal: true  


