apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: appset-of-appset
spec:
  goTemplate: true
  generators:
    - git:
        repoURL: https://github.com/ArnaudCHT/appset.git
        revision: main
        files:
        - path: "cluster/**/config.json"
  template:
    metadata:
      name: '{{.cluster.name}}-test-nettools'
    spec:
      project: '{{ .config.project }}'
      source:
        repoURL: '{{ .config.repoUrl }}'
        targetRevision: '{{ .config.targetRevision }}'
        path: app/setapp
        helm:
          valueFiles: 
            - "../../cluster/{{ .cluster.name }}/values.yaml"
      destination:
        server: '{{.cluster.address}}'
        namespace: infra-argo

