appset:
  clustername: cluster2
  argoProject: formation
  destination: https://api.dso-formation.hp.numerique-interieur.com:6443
  type: test
  default:
    ServerSideApply: true
    CreateNamespace: true
    repoUrl: "https://github.com/ArnaudCHT/appset.git"
    branch: "main"
    syncPolicy:
      autoSync: true
      prune: true
      selfHeal: true  

  customComponents:
    nginx:
      namespace: infra-nginx-system
      branch: main
    nettools:
      namespace: infra-nettools
