kind: Secret
apiVersion: v1
type: Opaque
metadata:
  name: myvaultsecret
  namespace: {{ include "nettools.namespace" . }}
  annotations:
    avp.kubernetes.io/remove-missing: "true"
data:
  test: <path:infra/data/test/infra#test | base64encode>