kind: Secret
apiVersion: v1
type: Opaque
metadata:
  name: my vault secret
  namespace: {{ include "nettools.namespace" . }}
  annotations:
    avp.kubernetes.io/remove-missing: "true"
data:
  test: <path:/test/vault/test/data/values#test | base64encode>